server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanch-coach/config-file.git
          default-label: main
          search-paths: wanch-coach